var localizedStrings = new Array;

localizedStrings['Quotes delayed by 20 minutes'] = 'Quotes delayed by 20 minutes';
localizedStrings['Done'] = 'Done';
localizedStrings['Remove'] = 'Remove';
localizedStrings['Quotes:'] = 'Quotes:';
localizedStrings['Failed to validate symbol'] = 'Failed to validate symbol';
localizedStrings['No results found'] = 'No results found';
localizedStrings['Validating symbol'] = 'Validating symbol';
localizedStrings['Retrieving Chart…'] = 'Retrieving Chart…';
localizedStrings['Error retrieving chart'] = 'Error retrieving chart';
localizedStrings['No Intraday Chart Available'] = 'No Intraday Chart Available';
localizedStrings['No chart data'] = 'No chart data';
localizedStrings['No response from server'] = 'No response from server';
localizedStrings['1d'] = '1d';
localizedStrings['1w'] = '1w';
localizedStrings['1m'] = '1m';
localizedStrings['3m'] = '3m';
localizedStrings['6m'] = '6m';
localizedStrings['1y'] = '1y';
localizedStrings['2y'] = '2y';
localizedStrings['Jan Feb Mar Apr May Jun Jul Aug Sep Oct Nov Dec'] = 'Jan Feb Mar Apr May Jun Jul Aug Sep Oct Nov Dec';
localizedStrings['Show change as a percentage'] = 'Show change as a percentage';
localizedStrings['Markets closed'] = 'Markets closed';
localizedStrings['Quotes just updated'] = 'Quotes just updated';
localizedStrings['Quotes last updated one minute ago'] = 'Quotes last updated one minute ago';
localizedStrings['Quotes last updated %@ minutes ago'] = 'Quotes last updated %@ minutes ago';
localizedStrings['Quotes last updated at %@'] = 'Quotes last updated at %@'; // time
localizedStrings['Quotes last updated on %@'] = 'Quotes last updated on %@'; // date
localizedStrings['Terms of Service'] = 'Terms of Service';
